import { spawnSync, execSync } from 'node:child_process';
import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import net from 'node:net';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const backend = path.join(root, 'backend');
const frontend = path.join(root, 'frontend');
const isWin = process.platform === 'win32';

export const PORT_RANGES = {
	api: { min: Number(process.env.API_PORT_MIN) || 8000, max: Number(process.env.API_PORT_MAX) || 8099 },
	web: { min: Number(process.env.WEB_PORT_MIN) || 5173, max: Number(process.env.WEB_PORT_MAX) || 5272 }
};

function isPortAvailable(port, host = '0.0.0.0') {
	return new Promise((resolve) => {
		const server = net.createServer();
		server.unref();
		server.once('error', () => resolve(false));
		server.listen({ port, host }, () => {
			server.close(() => resolve(true));
		});
	});
}

/** Pick the first free port in [min, max]. Skips ghost listeners on fixed ports. */
export async function findAvailablePort(min, max, host = '0.0.0.0') {
	for (let port = min; port <= max; port++) {
		if (await isPortAvailable(port, host)) return port;
	}
	throw new Error(`No free port between ${min} and ${max}`);
}

export async function allocateDevPorts() {
	const apiPort = await findAvailablePort(PORT_RANGES.api.min, PORT_RANGES.api.max);
	const webPort = await findAvailablePort(PORT_RANGES.web.min, PORT_RANGES.web.max);
	return { apiPort, webPort };
}

const VIRTUAL_IFACE = /hyper-v|virtual|vmware|virtualbox|vbox|wsl|npcap|loopback|tap-|tun |nordlynx|wireguard|bluetooth|warp|tailscale|zerotier|hamachi|vethernet/i;

/** Non-loopback IPv4 on real LAN adapters (skips VPN / virtual switches). */
export function getLanAddresses() {
	/** @type {Map<string, string>} */
	const ipToIface = new Map();
	for (const [name, entries] of Object.entries(os.networkInterfaces())) {
		if (VIRTUAL_IFACE.test(name)) continue;
		for (const entry of entries ?? []) {
			const family = entry.family;
			const isIPv4 = family === 'IPv4' || family === 4;
			if (!isIPv4 || entry.internal) continue;
			if (entry.address.startsWith('169.254.')) continue;
			ipToIface.set(entry.address, name);
		}
	}
	return [...ipToIface.entries()]
		.sort(([a], [b]) => a.localeCompare(b, undefined, { numeric: true }))
		.map(([address, iface]) => ({ address, iface }));
}

export function lanIpList(lanEntries = getLanAddresses()) {
	return lanEntries.map((e) => e.address);
}

export function primaryLanAddress(lanEntries = getLanAddresses()) {
	const ips = lanIpList(lanEntries);
	const pick = (prefix) => ips.find((ip) => ip.startsWith(prefix));
	const address = pick('192.168.') ?? pick('10.') ?? pick('172.') ?? ips[0] ?? null;
	if (!address) return null;
	return lanEntries.find((e) => e.address === address) ?? { address, iface: 'network' };
}

export function buildWebOrigins(webPort, lanEntries = getLanAddresses()) {
	const origins = new Set([
		`http://localhost:${webPort}`,
		`http://127.0.0.1:${webPort}`
	]);
	for (const { address } of lanEntries) {
		origins.add(`http://${address}:${webPort}`);
	}
	return [...origins];
}

export function buildAccessUrls({ apiPort, webPort, lanEntries = getLanAddresses() }) {
	const primaryLan = primaryLanAddress(lanEntries);
	const ips = lanIpList(lanEntries);
	return {
		lanEntries,
		lanAddresses: ips,
		primaryLan: primaryLan?.address ?? null,
		primaryLanIface: primaryLan?.iface ?? null,
		web: {
			localhost: `http://localhost:${webPort}`,
			loopback: `http://127.0.0.1:${webPort}`,
			lan: lanEntries.map(({ address, iface }) => ({
				url: `http://${address}:${webPort}`,
				address,
				iface
			}))
		},
		api: {
			loopback: `http://127.0.0.1:${apiPort}`,
			lan: ips.map((ip) => `http://${ip}:${apiPort}`)
		},
		ntfy: {
			localhost: 'http://localhost:2586',
			lan: ips.map((ip) => `http://${ip}:2586`)
		},
		appBaseUrl: primaryLan ? `http://${primaryLan.address}:${webPort}` : `http://localhost:${webPort}`
	};
}

export function writeDevPorts({ apiPort, webPort }) {
	const file = path.join(root, '.dev-ports.json');
	const access = buildAccessUrls({ apiPort, webPort });
	const apiUrl = access.api.loopback;
	writeFileSync(
		file,
		JSON.stringify(
			{
				apiPort,
				webPort,
				apiUrl,
				webUrl: access.web.localhost,
				webUrls: access.web,
				lanAddresses: access.lanAddresses,
				primaryLan: access.primaryLan,
				appBaseUrl: access.appBaseUrl,
				updatedAt: new Date().toISOString()
			},
			null,
			2
		)
	);
	// Keep Vite proxy in sync even if frontend/.env is stale.
	writeFileSync(
		path.join(frontend, '.env.local'),
		`# Auto-generated by npm run start:dev — do not commit\nAPI_PROXY_TARGET=${apiUrl}\n`
	);
	return file;
}

export function getPython() {
	const venvPython = isWin
		? path.join(backend, '.venv', 'Scripts', 'python.exe')
		: path.join(backend, '.venv', 'bin', 'python');

	if (!existsSync(venvPython)) {
		console.log('Creating Python virtual environment...');
		const py = isWin ? 'python' : 'python3';
		const result = spawnSync(py, ['-m', 'venv', path.join(backend, '.venv')], {
			stdio: 'inherit',
			cwd: root
		});
		if (result.status !== 0) process.exit(result.status ?? 1);
	}

	return venvPython;
}

export function apiEnv({ apiPort, webPort }) {
	const access = buildAccessUrls({ apiPort, webPort });
	return {
		...process.env,
		NTFY_BASE_URL: process.env.NTFY_BASE_URL || access.ntfy.localhost,
		APP_BASE_URL: process.env.APP_BASE_URL || access.appBaseUrl,
		CORS_ORIGINS: buildWebOrigins(webPort, access.lanAddresses).join(',')
	};
}

export function run(command, args, options = {}) {
	const result = spawnSync(command, args, { stdio: 'inherit', ...options });
	if (result.status !== 0) process.exit(result.status ?? 1);
}

export function tryRun(command, args, options = {}) {
	return spawnSync(command, args, { stdio: 'ignore', ...options });
}

function runNetsh(args) {
	return spawnSync('netsh', args, { encoding: 'utf8', shell: true });
}

function runPowerShell(command) {
	return spawnSync('powershell.exe', ['-NoProfile', '-Command', command], {
		encoding: 'utf8',
		shell: false
	});
}

const FIREWALL_RULE_NAMES = [
	'News Router Dev (Web)',
	'News Router Dev (API)',
	'News Router Dev (ntfy)'
];

/** Check whether firewall rules exist (no admin required). */
export function checkFirewallRules() {
	if (!isWin) return { ok: true, missing: [] };
	const missing = [];
	for (const name of FIREWALL_RULE_NAMES) {
		const show = runNetsh(['advfirewall', 'firewall', 'show', 'rule', `name=${name}`]);
		if (show.status !== 0 || !show.stdout?.includes(name)) {
			missing.push(name);
		}
	}
	return { ok: missing.length === 0, missing };
}

/** Set active Windows network adapters to Private (requires admin). */
export function setWindowsNetworkPrivate() {
	if (!isWin) return { ok: true, skipped: true };
	const result = runPowerShell(
		"Get-NetConnectionProfile | Where-Object { $_.NetworkCategory -ne 'Private' } | Set-NetConnectionProfile -NetworkCategory Private"
	);
	if (result.status !== 0) {
		const msg = (result.stderr || result.stdout || '').trim();
		return {
			ok: false,
			error: msg.includes('Access is denied') ? 'Administrator privileges required' : msg
		};
	}
	return { ok: true };
}

function addProgramFirewallRule(name, programPath, force) {
	if (!programPath || !existsSync(programPath)) return null;
	const show = runNetsh(['advfirewall', 'firewall', 'show', 'rule', `name=${name}`]);
	if (!force && show.status === 0 && show.stdout?.includes(name)) {
		return null;
	}
	runNetsh(['advfirewall', 'firewall', 'delete', 'rule', `name=${name}`]);
	const add = runNetsh([
		'advfirewall',
		'firewall',
		'add',
		'rule',
		`name=${name}`,
		'dir=in',
		'action=allow',
		`program=${programPath}`,
		'enable=yes',
		'profile=private,public'
	]);
	if (add.status !== 0) {
		const msg = (add.stderr || add.stdout || '').trim();
		throw new Error(
			msg.includes('requires elevation') || msg.includes('Access is denied')
				? 'Administrator privileges required'
				: msg || `netsh exited ${add.status}`
		);
	}
	return `${name} (${programPath})`;
}

/**
 * Allow inbound TCP on dev port ranges through Windows Firewall.
 * Requires Administrator for first-time setup.
 */
export function ensureWindowsFirewall({ force = false } = {}) {
	if (!isWin) return { ok: true, skipped: true, reason: 'not-windows' };
	if (process.env.NEWS_ROUTER_NO_FIREWALL === '1') {
		return { ok: true, skipped: true, reason: 'disabled' };
	}

	if (!force) {
		const existing = checkFirewallRules();
		if (existing.ok) return { ok: true, created: [] };
	}

	const network = setWindowsNetworkPrivate();
	if (!network.ok && network.error) {
		return { ok: false, error: network.error };
	}

	const { api, web } = PORT_RANGES;
	const rules = [
		{
			name: 'News Router Dev (Web)',
			port: `${web.min}-${web.max}`
		},
		{
			name: 'News Router Dev (API)',
			port: `${api.min}-${api.max}`
		},
		{
			name: 'News Router Dev (ntfy)',
			port: '2586'
		}
	];

	const created = [];
	if (network.ok && !network.skipped) {
		created.push('Network profile set to Private');
	}

	try {
		for (const rule of rules) {
			const show = runNetsh(['advfirewall', 'firewall', 'show', 'rule', `name=${rule.name}`]);
			if (!force && show.status === 0 && show.stdout?.includes(rule.name)) {
				continue;
			}
			runNetsh(['advfirewall', 'firewall', 'delete', 'rule', `name=${rule.name}`]);
			const add = runNetsh([
				'advfirewall',
				'firewall',
				'add',
				'rule',
				`name=${rule.name}`,
				'dir=in',
				'action=allow',
				'protocol=TCP',
				`localport=${rule.port}`,
				'enable=yes',
				'profile=private,public'
			]);
			if (add.status !== 0) {
				const msg = (add.stderr || add.stdout || '').trim();
				return {
					ok: false,
					error: msg.includes('requires elevation') || msg.includes('Access is denied')
						? 'Administrator privileges required'
						: msg || `netsh exited ${add.status}`
				};
			}
			created.push(`${rule.name} (TCP ${rule.port})`);
		}

		const nodeRule = addProgramFirewallRule('News Router Dev (Node.js)', process.execPath, force);
		if (nodeRule) created.push(nodeRule);

		const venvPython = path.join(backend, '.venv', 'Scripts', 'python.exe');
		const pythonRule = addProgramFirewallRule(
			'News Router Dev (Python)',
			existsSync(venvPython) ? venvPython : null,
			force
		);
		if (pythonRule) created.push(pythonRule);
	} catch (err) {
		return { ok: false, error: err instanceof Error ? err.message : String(err) };
	}

	return { ok: true, created };
}

export function getWindowsNetworkHint() {
	if (!isWin) return null;
	try {
		const out = execSync(
			'powershell -NoProfile -Command "Get-NetConnectionProfile | Select-Object -ExpandProperty NetworkCategory"',
			{ encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] }
		).trim();
		if (out.includes('Public')) {
			return 'Your Wi‑Fi/Ethernet is set to Public — Windows may block LAN access. Settings → Network → set profile to Private.';
		}
	} catch {
		// ignore
	}
	return null;
}

/** @deprecated Use allocateDevPorts() — kept for manual cleanup only. */
export function freePort(port) {
	const pids = new Set();

	if (isWin) {
		try {
			const out = execSync(`netstat -ano -p tcp | findstr :${port}`, {
				encoding: 'utf8',
				stdio: ['pipe', 'pipe', 'ignore']
			});
			for (const line of out.split('\n')) {
				if (!line.includes('LISTENING')) continue;
				const parts = line.trim().split(/\s+/);
				const localAddress = parts[1] ?? '';
				if (!localAddress.endsWith(`:${port}`)) continue;
				const pid = parts.at(-1);
				if (pid && /^\d+$/.test(pid) && pid !== '0') pids.add(pid);
			}
		} catch {
			return;
		}
		for (const pid of pids) {
			try {
				console.log(`Stopping old process ${pid} on port ${port}...`);
				execSync(`taskkill /F /PID ${pid}`, { stdio: 'ignore' });
			} catch {
				// already exited
			}
		}
		return;
	}

	try {
		const out = execSync(`lsof -ti tcp:${port}`, { encoding: 'utf8' }).trim();
		if (!out) return;
		for (const pid of out.split('\n').filter(Boolean)) {
			console.log(`Stopping old process ${pid} on port ${port}...`);
			tryRun('kill', ['-9', pid]);
		}
	} catch {
		// port free
	}
}

export async function waitForApi(apiPort, attempts = 40) {
	const url = `http://127.0.0.1:${apiPort}/api/health`;
	for (let i = 0; i < attempts; i++) {
		try {
			const response = await fetch(url);
			if (!response.ok) continue;
			const body = await response.json();
			if (body?.poll_api_version === 2) return true;
		} catch {
			// not ready
		}
		await new Promise((resolve) => setTimeout(resolve, 250));
	}
	return false;
}

export async function waitForWeb(webPort, attempts = 60) {
	const url = `http://127.0.0.1:${webPort}`;
	for (let i = 0; i < attempts; i++) {
		try {
			const response = await fetch(url, { redirect: 'manual' });
			if (response.ok || response.status === 304 || response.status === 302) return true;
		} catch {
			// not ready
		}
		await new Promise((resolve) => setTimeout(resolve, 250));
	}
	return false;
}

/** Probe the LAN IP from this PC — confirms 0.0.0.0 bind, not firewall from phone. */
export async function probeLanWeb(webPort, lanIp) {
	if (!lanIp) return { ok: false, reason: 'no-lan-ip' };
	try {
		const response = await fetch(`http://${lanIp}:${webPort}`, {
			redirect: 'manual',
			signal: AbortSignal.timeout(5000)
		});
		if (response.ok || response.status === 304 || response.status === 302) {
			return { ok: true };
		}
		return { ok: false, reason: `HTTP ${response.status}` };
	} catch (err) {
		return { ok: false, reason: err instanceof Error ? err.message : String(err) };
	}
}

export function isPortListening(port, host = '0.0.0.0') {
	return new Promise((resolve) => {
		const socket = net.createConnection({ port, host: host === '0.0.0.0' ? '127.0.0.1' : host });
		socket.setTimeout(1500);
		socket.once('connect', () => {
			socket.destroy();
			resolve(true);
		});
		socket.once('timeout', () => {
			socket.destroy();
			resolve(false);
		});
		socket.once('error', () => resolve(false));
	});
}

/** Stop leftover dev servers from a previous session (common on Windows). */
export function freeDevPorts() {
	for (let port = PORT_RANGES.api.min; port <= Math.min(PORT_RANGES.api.min + 5, PORT_RANGES.api.max); port++) {
		freePort(port);
	}
	for (let port = PORT_RANGES.web.min; port <= Math.min(PORT_RANGES.web.min + 5, PORT_RANGES.web.max); port++) {
		freePort(port);
	}
}

export function setup() {
	const python = getPython();
	const pip = isWin
		? path.join(backend, '.venv', 'Scripts', 'pip.exe')
		: path.join(backend, '.venv', 'bin', 'pip');

	console.log('Installing backend dependencies...');
	run(pip, ['install', '-q', '-r', path.join(backend, 'requirements.txt')]);

	mkdirSync(path.join(backend, 'data'), { recursive: true });

	if (!existsSync(path.join(frontend, 'node_modules'))) {
		console.log('Installing frontend dependencies...');
		run(isWin ? 'npm.cmd' : 'npm', ['install'], { cwd: frontend, shell: isWin });
	}
}

export function startNtfy() {
	const check = tryRun('docker', ['info']);
	if (check.status !== 0) {
		console.warn('Docker not available — push notifications disabled (install Docker for ntfy).');
		return;
	}

	const container = 'news-router-ntfy';
	const existing = execSync(`docker ps -a --filter name=^${container}$ --format "{{.Names}}"`, {
		encoding: 'utf8',
		stdio: ['ignore', 'pipe', 'ignore']
	}).trim();

	if (existing === container) {
		tryRun('docker', ['start', container]);
	} else {
		console.log('Starting ntfy container...');
		run('docker', ['run', '-d', '--name', container, '-p', '2586:80', 'binwiederhier/ntfy', 'serve']);
	}
}

export function printBanner({ apiPort, webPort, firewallOk = null, lanProbe = null } = {}) {
	const access = buildAccessUrls({ apiPort, webPort });
	const networkHint = getWindowsNetworkHint();
	const firewallCheck = firewallOk === null && isWin ? checkFirewallRules() : null;
	const blocked = firewallOk === false || firewallCheck?.ok === false;

	console.log('');
	console.log('  News Router — listening on all interfaces (0.0.0.0)');
	console.log('');
	console.log('  This computer');
	console.log(`    Web     ${access.web.localhost}`);
	console.log(`            ${access.web.loopback}`);
	console.log(`    API     ${access.api.loopback}  (via web proxy: /api/*)`);
	console.log(`    ntfy    ${access.ntfy.localhost}`);

	if (access.web.lan.length > 0) {
		console.log('');
		console.log('  Other devices on your network (same Wi‑Fi, not guest/VPN)');
		for (const entry of access.web.lan) {
			const label = entry.iface ? `  (${entry.iface})` : '';
			console.log(`    Web     ${entry.url}${label}`);
		}
		if (access.primaryLan) {
			console.log(`    ntfy    http://${access.primaryLan}:2586`);
		}
	} else {
		console.log('');
		console.log('  LAN: no usable IPv4 found — connect Wi‑Fi/Ethernet or disable VPN.');
	}

	console.log('');
	console.log(`  Digest / push links use ${access.appBaseUrl}`);

	if (networkHint || blocked) {
		console.log('');
		if (networkHint) console.log(`  ⚠ ${networkHint}`);
		if (blocked) {
			console.log('  ⚠ Windows Firewall has no rules for News Router yet.');
			console.log('    Run once (UAC prompt):  npm run fix-lan');
			console.log('    Then restart:           npm run start:dev');
		}
	}

	if (isWin && access.web.lan.length > 0 && !blocked && firewallOk === true) {
		console.log('');
		console.log('  ✓ Windows Firewall allows LAN access on dev ports.');
	}

	if (lanProbe?.ok === true && access.primaryLan) {
		console.log('');
		console.log(`  ✓ Server reachable at http://${access.primaryLan}:${webPort} from this PC.`);
	} else if (lanProbe?.ok === false && access.primaryLan) {
		console.log('');
		console.log(`  ⚠ Could not reach http://${access.primaryLan}:${webPort} on this PC (${lanProbe.reason}).`);
		console.log('    Check that the dev server is still running.');
	}

	console.log('');
}

export { root, backend, frontend, isWin };
